{
 "title": "HW 8",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Third-party API hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(my_service_hits_third_party[1m])",
     "legendFormat": "{{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Third-party API timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "my_service_timings_third_party{quantile=\"0.99\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Service hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(my_service_hits{path=\"/thread\"}[1m])",
     "legendFormat": "{{path}} - {{status}}"
    },
    {
     "expr": "increase(my_service_hits{path=\"/thread/thread\"}[1m])",
     "legendFormat": "{{path}} - {{status}}"
    },
    {
     "expr": "increase(my_service_hits{path=\"/thread/thread/comment\"}[1m])",
     "legendFormat": "{{path}} - {{status}}"
    },
    {
     "expr": "increase(my_service_hits{path=\"/thread/thread/comment/comment/like\"}[1m])",
     "legendFormat": "{{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Service timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.99, my_service_timings{path=\"/thread\"})",
     "legendFormat": "/thread"
    },
    {
     "expr": "quantile(0.99, my_service_timings{path=\"/thread/thread\"})",
     "legendFormat": "/thread/thread"
    },
    {
     "expr": "quantile(0.99, my_service_timings{path=\"/thread/thread/comment\"})",
     "legendFormat": "/thread/thread/comment"
    },
    {
     "expr": "quantile(0.99, my_service_timings{path=\"/thread/thread/comment/comment/like\"})",
     "legendFormat": "/thread/thread/comment/comment/like"
    }
   ]
  }
 ]
}